---
- name: Install Python & Docker
  hosts: managers:workers
  gather_facts: False
  roles:
    - python
    - docker

- name: Init Swarm cluster
  hosts: managers
  gather_facts: False
  roles:
    - swarm-init

- name: Join Swarm cluster
  hosts: workers
  gather_facts: False
  vars:
      token: "{{ hostvars[groups['managers'][0]]['worker_token']['stdout'] }}"
      manager: "{{ hostvars[groups['managers'][0]]['inventory_hostname'] }}"
  roles:
    - swarm-join